# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Qoyyuum's Blog
description: > # this means to ignore newlines until "baseurl:"
  A blog about a Bruneian Web Developer exploring the Internet and sharing about it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.qoyyuum.me" # the base hostname & protocol for your site
twitter_username: Qoyyuum
github_username:  Qoyyuum

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-hacker