# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Qoyyuum's Blog
email: 
description: > # this means to ignore newlines until "baseurl:"
  This blog is my personal view of what I find online. My personal experience is meant
  for everyone to take as a lesson or pointers into whatever direction that you may
  call *progress*. This blog serves as my notes, my thoughts, my opinions and my experience
  while surfing the interwebs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "qoyyuum.github.io" # the base hostname & protocol for your site
twitter_username: qoyyuum
github_username:  qoyyuum

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-hacker
